const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
(async () => {
 const pages = await (await fetch('http://127.0.0.1:9223/json')).json();
 const ws = new WebSocket(pages.find(p => p.type === 'page').webSocketDebuggerUrl);
 await new Promise(r => ws.addEventListener('open', r, {once:true}));
 let next = 0; const pending = new Map(), errors = [], requests = [];
 ws.addEventListener('message', event => { const message = JSON.parse(event.data); if(message.id) { const item = pending.get(message.id); pending.delete(message.id); message.error ? item.reject(message.error) : item.resolve(message.result); } if(message.method === 'Runtime.exceptionThrown') errors.push(message.params); if(message.method === 'Network.requestWillBeSent') requests.push(message.params.request.url); });
 const send = (method,params={}) => new Promise((resolve,reject) => { const id = ++next; pending.set(id,{resolve,reject}); ws.send(JSON.stringify({id,method,params})); });
 const read = async expression => (await send('Runtime.evaluate',{expression,returnByValue:true})).result.value;
 const readClipboard = async () => {
  await send('Browser.grantPermissions',{permissions:['clipboardReadWrite','clipboardSanitizedWrite']});
  const result = await send('Runtime.evaluate',{expression:'navigator.clipboard.readText()',returnByValue:true,awaitPromise:true});
  assert.equal(result.exceptionDetails,undefined,'Clipboard read failed');
  // Windows normalizes clipboard line endings to CRLF.
  return result.result.value.replace(/\r\n/g,'\n');
 };
 const click = async id => { const root = await send('DOM.getDocument'); const node = await send('DOM.querySelector',{nodeId:root.root.nodeId,selector:'#'+id}); await send('DOM.scrollIntoViewIfNeeded',{nodeId:node.nodeId}); await send('Runtime.evaluate',{expression:'new Promise(resolve => requestAnimationFrame(() => resolve(true)))',awaitPromise:true}); const box = await read(`(()=>{const r=document.getElementById('${id}').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`); await send('Input.dispatchMouseEvent',{type:'mousePressed',...box,button:'left',clickCount:1}); await send('Input.dispatchMouseEvent',{type:'mouseReleased',...box,button:'left',clickCount:1}); };
 await send('Runtime.enable'); await send('Network.enable'); await send('Page.enable');
 await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'dark'}]});
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
 const loaded = new Promise(resolve => { const listener = event => { if(JSON.parse(event.data).method === 'Page.loadEventFired') { ws.removeEventListener('message',listener); resolve(); } }; ws.addEventListener('message',listener); });
 await send('Page.navigate',{url:pathToFileURL(path.resolve('index.html')).href}); await loaded;
 await send('Runtime.evaluate',{expression:'Promise.all(document.getAnimations().map(animation => animation.finished)).then(() => true)',awaitPromise:true});
 assert.equal(await read("document.getElementById('copy').disabled"),true);
 assert.equal(await read("document.documentElement.dataset.theme"),'dark');
 assert.equal(await read("document.getElementById('theme-toggle').getAttribute('aria-pressed')"),'true');
 await click('theme-toggle'); assert.equal(await read("document.documentElement.dataset.theme"),'light');
 await click('theme-toggle'); assert.equal(await read("document.documentElement.dataset.theme"),'dark');
 assert.equal(await read("document.querySelector('.settings').open"),false);
 assert.match(await read("document.querySelector('.privacy-assurance').textContent"),/Nothing is uploaded/);
 assert.match(await read("document.querySelector('.restore-intro').textContent"),/last copied prompt/);
 await click('customize-details'); assert.equal(await read("document.querySelector('.settings').open"),true);
 await click('customize-details'); assert.equal(await read("document.querySelector('.settings').open"),false);
 await click('example-it');
 assert.match(await read("document.getElementById('output').textContent"),/\[NAME_1\]/);
 assert.match(await read("document.getElementById('output').textContent"),/\[EMAIL_1\]/);
 assert.doesNotMatch(await read("document.getElementById('output').textContent"),/alex.morgan@example.com/);
 assert.match(await read("document.getElementById('output').textContent"),/\[PATH_1\]/);
 await click('customize-details'); assert.equal(await read("document.querySelector('.settings').open"),true);
 await click('path-category'); assert.match(await read("document.getElementById('output').textContent"),/fileserver/);
 await click('path-category'); assert.doesNotMatch(await read("document.getElementById('output').textContent"),/fileserver/);
 await click('customize-details');
 assert.equal(await read("document.querySelector('.settings').open"),false);
 await click('clear');
 await click('source'); await send('Input.insertText',{text:'Ticket reference: qrtz991'});
 assert.match(await read("document.getElementById('output').textContent"),/qrtz991/);
 await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Shift',code:'ShiftLeft',windowsVirtualKeyCode:16,nativeVirtualKeyCode:16});
 for(let i=0;i<7;i++) {
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowLeft',code:'ArrowLeft',modifiers:8,windowsVirtualKeyCode:37,nativeVirtualKeyCode:37});
  await send('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowLeft',code:'ArrowLeft',modifiers:8,windowsVirtualKeyCode:37,nativeVirtualKeyCode:37});
 }
 await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Shift',code:'ShiftLeft',modifiers:8,windowsVirtualKeyCode:16,nativeVirtualKeyCode:16});
 assert.equal(await read("document.getElementById('source').value.slice(document.getElementById('source').selectionStart,document.getElementById('source').selectionEnd)"),'qrtz991');
 await click('protect-selection');
 assert.match(await read("document.getElementById('output').textContent"),/\[MANUAL_1\]/);
 assert.doesNotMatch(await read("document.getElementById('output').textContent"),/qrtz991/);
 await click('copy'); await click('ai-reply');
 await send('Input.insertText',{text:'Found [MANUAL_1].'});
 assert.match(await read("document.getElementById('restored-output').textContent"),/Found qrtz991\./);
 await click('clear');
 await click('example-it');
 fs.mkdirSync('tests/artifacts',{recursive:true});
 const luminance = color => {
  const channels = color.match(/[\d.]+/g).slice(0,3).map(Number).map(n => { const v=n/255; return v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4; });
  return channels[0]*0.2126+channels[1]*0.7152+channels[2]*0.0722;
 };
 for (const theme of ['dark','light']) {
  if(await read('document.documentElement.dataset.theme') !== theme) await click('theme-toggle');
  await new Promise(r=>setTimeout(r,200));
  const pairs = await read(`(()=>{
   const background = el => { for(let node=el;node;node=node.parentElement){const color=getComputedStyle(node).backgroundColor;if(color!=='rgba(0, 0, 0, 0)'&&color!=='transparent')return color;}return 'rgb(255,255,255)'; };
   return ['body','.intro','.mode-preview','.chip','.output mark','.primary','.secondary','.notice','.notice strong','.footer','.editor-meta','.privacy-assurance','.privacy-details','.settings summary','#protect-selection'].map(selector=>{const el=document.querySelector(selector);return {selector,color:getComputedStyle(el).color,background:background(el)};}).concat([{selector:'textarea placeholder',color:getComputedStyle(document.getElementById('source'),'::placeholder').color,background:background(document.getElementById('source'))}]);
  })()`);
  for(const pair of pairs){const a=luminance(pair.color),b=luminance(pair.background);const contrast=(Math.max(a,b)+0.05)/(Math.min(a,b)+0.05);assert.ok(contrast>=4.5,`${theme} ${pair.selector} contrast ${contrast.toFixed(2)}`);}
  await new Promise(r=>setTimeout(r,200));
  fs.writeFileSync(`tests/artifacts/palette-${theme}.png`,Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:1440,height:1390,scale:1}})).data,'base64'));
 }
 await click('theme-toggle');
 await new Promise(r => setTimeout(r,500));
 fs.writeFileSync('tests/artifacts/desktop.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
 await click('example-education');
 assert.doesNotMatch(await read("document.getElementById('output').textContent"),/Jamie Smith|STU-2048|Northside Academy|school-server/);
 assert.match(await read("document.getElementById('output').textContent"),/\[PATH_1\]/);
 await click('example-payroll');
 assert.doesNotMatch(await read("document.getElementById('output').textContent"),/Taylor Reed|EMP-1042|finance.local|Payroll Reports/);
 await click('example-it');
 await click('redact-mode'); assert.match(await read("document.getElementById('output').textContent"),/al\*+an@example\.com/);
 assert.doesNotMatch(await read("document.getElementById('output').textContent"),/\[EMAIL_1\]/);
 await click('review'); assert.equal(await read("document.getElementById('info-dialog').open"),true);
 await click('close-dialog'); await click('mask-mode');
 await click('custom'); await send('Input.insertText',{text:'Alex'}); await click('add-custom');
 assert.doesNotMatch(await read("document.getElementById('output').textContent"),/\bAlex\b/);
 await click('copy');
 for(let i=0;i<40;i++) { if(/copied|Clipboard unavailable/.test(await read("document.getElementById('toast').textContent"))) break; await new Promise(r => setTimeout(r,50)); }
 assert.match(await read("document.getElementById('toast').textContent"),/copied|Clipboard unavailable/);
 const copiedPrompt = await read("document.getElementById('output').textContent");
 const nameToken = copiedPrompt.match(/Name: (\[[^\]]+\])/)[1];
 const emailToken = copiedPrompt.match(/Email: (\[[^\]]+\])/)[1];
 const pathToken = copiedPrompt.match(/Share: (\[[^\]]+\])/)[1];
 const noFieldsReply = 'Check the permissions, reconnect the drive, and try again.';
 await click('ai-reply'); await send('Input.insertText',{text:noFieldsReply});
 assert.equal(await read("document.getElementById('restored-output').textContent.trimEnd()"),noFieldsReply);
 assert.equal(await read("document.getElementById('restore-count').textContent"),'Reply unchanged');
 assert.equal(await read("document.getElementById('copy-restored-label').textContent"),'Copy reply');
 assert.match(await read("document.getElementById('restore-help').textContent"),/No matching protected fields/);
 await click('restore-reply');
 assert.match(await read("document.getElementById('toast').textContent"),/No matching protected fields/);
 await click('clear-reply');
 await click('ai-reply');
 await send('Input.insertText',{text:`<img src=x onerror=alert(1)> Hello ${nameToken}. Email ${emailToken}. Open ${pathToken}. Leave [EMAIL_99].`});
 await click('restore-reply');
 assert.match(await read("document.getElementById('restored-output').textContent"),/Alex Morgan/);
 assert.match(await read("document.getElementById('restored-output').textContent"),/alex.morgan@example.com/);
 assert.match(await read("document.getElementById('restored-output').textContent"),/fileserver/);
 assert.match(await read("document.getElementById('restore-issues').textContent"),/1 unknown labels/);
 assert.equal(await read("document.querySelectorAll('#restored-output img').length"),0);
 const restoreBox = await read("(()=>{const r=document.querySelector('.restore-workspace').getBoundingClientRect();return {x:r.x+scrollX,y:r.y+scrollY,width:r.width,height:r.height,scale:1}})()");
 fs.writeFileSync('tests/artifacts/restoration.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:restoreBox})).data,'base64'));
 await click('redact-mode');
 assert.match(await read("document.getElementById('restored-output').textContent"),/alex.morgan@example.com/);
 await click('copy-restored');
 for(let i=0;i<40;i++) { if(/Restored reply copied|Clipboard unavailable/.test(await read("document.getElementById('toast').textContent"))) break; await new Promise(r => setTimeout(r,50)); }
 assert.match(await read("document.getElementById('toast').textContent"),/Restored reply copied|Clipboard unavailable/);
 await click('source');
 await send('Input.dispatchKeyEvent',{type:'keyDown',key:'a',code:'KeyA',modifiers:2});
 await send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',modifiers:2});
 await send('Input.insertText',{text:'Email: another@example.com'});
 assert.match(await read("document.getElementById('restored-output').textContent"),/alex.morgan@example.com/);
 await click('clear'); assert.equal(await read("document.getElementById('source').value"),'');
 assert.equal(await read("document.getElementById('ai-reply').value"),'');
 assert.equal(await read("document.getElementById('mapping-badge').textContent"),'Waiting for copied prompt');
 assert.equal(await read("document.getElementById('copy').textContent.includes('Copy protected prompt')"),true);
 assert.equal(await read("document.querySelector('#protect')===null"),true);
 await click('source'); await send('Input.insertText',{text:'Email: alex.morgan@example.test'});
 assert.match(await read("document.getElementById('output').textContent"),/al\*{7}an@example\.test/);
 await click('copy'); await click('ai-reply'); await send('Input.insertText',{text:'Reply to al*******an@example.test.'});
 assert.equal(await read("document.getElementById('restored-output').textContent.trimEnd()"),'Reply to alex.morgan@example.test.');
 await click('clear');
 await click('mask-mode');
 await click('source'); await send('Input.insertText',{text:'<img src=x onerror=alert(1)> Contact: Jamie Smith. Email jamie@example.com.'});
 assert.equal(await read("document.querySelectorAll('#output img').length"),0);
 assert.match(await read("document.getElementById('output').textContent"),/\[NAME_1\]/);
 await click('clear');
 const markdown = '# Request\n\n**Email:** alex@example.com\n\n- First step\n- Second step\n\n| Task | State |\n| --- | --- |\n| Review | Ready |\n\n```text\nKeep **literal** code\n```';
 const protectedMarkdown = markdown.replace('alex@example.com','[EMAIL_1]');
 await click('source'); await send('Input.insertText',{text:markdown});
 await click('source-preview-button');
 assert.equal(await read("document.getElementById('source').hidden"),true);
 assert.equal(await read("document.querySelector('#source-preview h1').textContent"),'Request');
 assert.equal(await read("document.getElementById('source').value"),markdown);
 assert.equal(await read("document.querySelector('#output strong').textContent"),'Email:');
 assert.equal(await read("document.querySelector('#output mark').textContent"),'[EMAIL_1]');
 assert.equal(await read("document.querySelectorAll('#output table').length"),1);
 await click('copy');
 for(let i=0;i<40;i++) { if(/copied|Clipboard unavailable/.test(await read("document.getElementById('toast').textContent"))) break; await new Promise(r => setTimeout(r,50)); }
 assert.match(await read("document.getElementById('toast').textContent"),/Protected text copied/);
 await click('ai-reply');
 const copiedMarkdown = await readClipboard();
 assert.equal(copiedMarkdown,protectedMarkdown);
 await send('Input.insertText',{text:copiedMarkdown});
 assert.equal(await read("document.getElementById('ai-reply').value"),protectedMarkdown);
 await click('ai-reply-preview-button');
 assert.equal(await read("document.querySelector('#ai-reply-preview h1').textContent"),'Request');
 assert.equal(await read("document.querySelector('#restored-output h1').textContent"),'Request');
 assert.match(await read("document.getElementById('restored-output').textContent"),/alex@example.com/);
 await click('copy-restored');
 for(let i=0;i<40;i++) { if(/Restored reply copied/.test(await read("document.getElementById('toast').textContent"))) break; await new Promise(r => setTimeout(r,50)); }
 const copiedRestoredMarkdown = await readClipboard();
 assert.equal(copiedRestoredMarkdown,markdown);
 fs.writeFileSync('tests/artifacts/markdown.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
 await click('clear'); await click('source');
 await send('Input.insertText',{text:copiedRestoredMarkdown});
 assert.equal(await read("document.getElementById('source').value"),markdown);
 await click('source-preview-button');
 for(const width of [320,768,1024,1440]) { await send('Emulation.setDeviceMetricsOverride',{width,height:1050,deviceScaleFactor:1,mobile:false}); assert.equal(await read('document.documentElement.scrollWidth > innerWidth'),false,`Overflow at ${width}`); assert.notEqual(await read("getComputedStyle(document.getElementById('theme-toggle')).display"),'none'); if(width === 320) fs.writeFileSync('tests/artifacts/mobile.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64')); }
 assert.equal(errors.length,0,JSON.stringify(errors));
 assert.equal(requests.filter(url => /^https?:/.test(url)).length,0);
 assert.equal(await read("[...document.querySelectorAll('button')].every(button => button.getAttribute('aria-label') || button.textContent.trim())"),true,'Every button has an accessible name');
 assert.equal(await read("document.querySelector('label[for=source]')!==null && document.querySelector('label[for=ai-reply]')!==null"),true,'Text editors have visible labels');
 console.log('Browser checks passed: redaction, restoration, Markdown in all four panels, exact Markdown clipboard round trip, themes, literal HTML, 4 responsive widths, zero runtime errors, zero external requests.');
 ws.close();
})().catch(error => {console.error(error);process.exit(1)});
